### ISSUE TITLE
cannot install jupyter with conda

### ISSUE THREAD

**Issue by dridk** [igvteam/igv.js-jupyter#10]
```
source activate bioinfo 
conda install -c igv igv 
// or 
python setup.py install 
jupyter-nbextension install igv
Traceback (most recent call last):
  File "/home/sacha/miniconda3/envs/bioinfo/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/home/sacha/miniconda3/envs/bioinfo/lib/python3.6/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/sacha/miniconda3/envs/bioinfo/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/sacha/miniconda3/envs/bioinfo/lib/python3.6/site-packages/notebook/nbextensions.py", line 988, in start
    super(NBExtensionApp, self).start()
  File "/home/sacha/miniconda3/envs/bioinfo/lib/python3.6/site-packages/jupyter_core/application.py", line 255, in start
    self.subapp.start()
  File "/home/sacha/miniconda3/envs/bioinfo/lib/python3.6/site-packages/notebook/nbextensions.py", line 716, in start
    self.install_extensions()
  File "/home/sacha/miniconda3/envs/bioinfo/lib/python3.6/site-packages/notebook/nbextensions.py", line 695, in install_extensions
    **kwargs
  File "/home/sacha/miniconda3/envs/bioinfo/lib/python3.6/site-packages/notebook/nbextensions.py", line 126, in install_nbextension
    ensure_dir_exists(nbext)
  File "/home/sacha/miniconda3/envs/bioinfo/lib/python3.6/site-packages/jupyter_core/utils/__init__.py", line 13, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/home/sacha/miniconda3/envs/bioinfo/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/home/sacha/miniconda3/envs/bioinfo/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/usr/local/share/jupyter'

```

**Comment by jrobinso** [comment]
Do you have write permissions to /usr/local/share/jupyter  ?

**Comment by ishanley** [comment]
Might try:

`jupyter nbextension install igv --py --user`
